"""Ignore-filtering behavior, including the git-backed path: git
check-ignore for .gitignore matching, and git ls-files for the
tracked-files-only filter (not just the pathspec fallback the fixture
normally exercises, since it has no .git of its own).
"""

import shutil
import subprocess
from pathlib import Path

import pytest

from readmetree import cli, prompt
from readmetree.commands._shared import scan_project
from readmetree.config import ProjectConfig
from readmetree import scanner


def _git_available() -> bool:
    try:
        subprocess.run(["git", "--version"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return True
    except OSError:
        return False


requires_git = pytest.mark.skipif(not _git_available(), reason="git not installed")


@requires_git
def test_git_backed_ignore_matches_pathspec_fallback_once_committed(
    example_project: Path, monkeypatch, tmp_path
):
    # example_project (from conftest) has no .git -> pathspec fallback.
    monkeypatch.setattr(prompt, "prompt_for_new_paths", lambda items: {})
    assert cli.main(["generate", "--root", str(example_project)]) == 0
    fallback_readme = (example_project / "README.md").read_text(encoding="utf-8")

    git_project = tmp_path / "git_copy"
    shutil.copytree(example_project, git_project)
    subprocess.run(["git", "init", "-q"], cwd=git_project, check=True)
    subprocess.run(["git", "add", "-A"], cwd=git_project, check=True)
    subprocess.run(
        ["git", "-c", "user.email=a@b.c", "-c", "user.name=t", "commit", "-q", "-m", "x"],
        cwd=git_project,
        check=True,
    )

    assert cli.main(["generate", "--root", str(git_project)]) == 0
    git_readme = (git_project / "README.md").read_text(encoding="utf-8")

    assert git_readme == fallback_readme


@requires_git
def test_untracked_file_is_excluded_in_a_git_repo(tmp_path: Path):
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    (tmp_path / "tracked.txt").write_text("", encoding="utf-8")
    (tmp_path / "scratch.txt").write_text("", encoding="utf-8")
    subprocess.run(["git", "add", "tracked.txt"], cwd=tmp_path, check=True)

    config = ProjectConfig.load(tmp_path / ".readmetree.yml")
    node = scan_project(tmp_path, config)
    keys = [k for k, _, _ in scanner.iter_entries(node)]

    assert keys == ["tracked.txt"]


@requires_git
def test_untracked_file_still_shown_via_force_include(tmp_path: Path):
    from readmetree.config import ForceIncludeSpec

    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    (tmp_path / "generated.log").write_text("", encoding="utf-8")

    config = ProjectConfig()
    config.force_include = [ForceIncludeSpec(pattern="generated.log")]

    node = scan_project(tmp_path, config)
    keys = [k for k, _, _ in scanner.iter_entries(node)]

    assert keys == ["generated.log"]


@requires_git
def test_untracking_a_file_does_not_delete_its_description(tmp_path: Path, monkeypatch):
    """A file that's still on disk but drops out of `git ls-files` (git rm
    --cached, or simply not yet re-added on a branch switch) must keep its
    hand-written description — it isn't gone, just hidden from the tree
    for now, and the description can't be regenerated by asking again.
    """
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    (tmp_path / "a.txt").write_text("", encoding="utf-8")
    subprocess.run(["git", "add", "a.txt"], cwd=tmp_path, check=True)

    monkeypatch.setattr(prompt, "prompt_for_new_paths", lambda items: {"a.txt": "hand-written note"})
    assert cli.main(["generate", "--root", str(tmp_path)]) == 0
    assert ProjectConfig.load(tmp_path / ".readmetree.yml").get_description("a.txt") == "hand-written note"

    # File stays on disk but is untracked from the index.
    subprocess.run(["git", "rm", "-q", "--cached", "a.txt"], cwd=tmp_path, check=True)

    assert cli.main(["generate", "--root", str(tmp_path)]) == 0

    config_after = ProjectConfig.load(tmp_path / ".readmetree.yml")
    assert config_after.get_description("a.txt") == "hand-written note"
    readme = (tmp_path / "README.md").read_text(encoding="utf-8")
    assert "a.txt" not in readme  # hidden from the rendered tree, but not deleted


@requires_git
def test_git_worktree_with_file_based_dotgit_still_uses_tracked_filter(tmp_path: Path):
    """.git is a *file* (not a directory) inside a worktree/submodule —
    tracked-files filtering must still activate there, not silently fall
    back to "show everything not .gitignore'd".
    """
    main_repo = tmp_path / "main"
    main_repo.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=main_repo, check=True)
    (main_repo / "a.txt").write_text("", encoding="utf-8")
    subprocess.run(["git", "add", "-A"], cwd=main_repo, check=True)
    subprocess.run(
        ["git", "-c", "user.email=a@b.c", "-c", "user.name=t", "commit", "-q", "-m", "x"],
        cwd=main_repo,
        check=True,
    )

    worktree = tmp_path / "wt"
    subprocess.run(
        ["git", "worktree", "add", "-q", str(worktree), "-b", "wt-branch"],
        cwd=main_repo,
        check=True,
    )
    assert (worktree / ".git").is_file()  # not a directory — the whole point

    (worktree / "scratch.txt").write_text("", encoding="utf-8")  # untracked

    config = ProjectConfig.load(worktree / ".readmetree.yml")
    node = scan_project(worktree, config)
    keys = [k for k, _, _ in scanner.iter_entries(node)]

    assert keys == ["a.txt"]
